gitea:
    dbpass: ENC[AES256_GCM,data:E+f5TapsgXt4uFqJDyDMHPJkjTZEiN2tLa9r2SdACvoQZkHL6XuXjQ==,iv:+KNkPw6g7CG3tCr0UKC2X7D4mfLUG5FBVYZS3EbBacs=,tag:oY2szsQSQubUePEbKkrw6Q==,type:str]
nextcloud:
    adminpass: ENC[AES256_GCM,data:6OcwuyIcrE6OtWdGlDTf03eVb1zUg91Y7TyN4sVGHvpSoKly3wq83Q==,iv:tqPqtB+16eXgriMxwWtMKB/tb5mMLHSROVWK8RZCS40=,tag:ioKVqRKda6BcRtI60B6KJA==,type:str]
    dbpass: ENC[AES256_GCM,data:AoVN0qt8aYhJNaW8/DV8FA9ao4I817FqCXdGv93gRqr5wKYbu54YsQ==,iv:AFILBggNgfhncdP0Sajjld+RjoohSmBtiagLEhrHWaM=,tag:hy7xacEOosBCHcW4LUm/zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r58ljwth4np2hfh7gyyxw7y2zarwpwukuvnzehw8hgaa4kphtehs5gswdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MzFyM0lRV2pRZlhGQ0x6
            UGtvZG83SFM5b2JTK09zS1duOHV3WDJqTXdRClpMT0FEV0E3OHF0UTRFM2ZTWkVr
            dUMyZFo1QkprUmNOSllha0ZXN2NrbDAKLS0tIElHeUJEUmQ0cUJDeUE1SGlMQm9R
            Uk92R3RpRVRPMXAxTHdBN01GcmRwcEkKDcwdcoiDCRWJrXOeMTSeWGigZao2U5N2
            jsbKD/tzZwK6VKmp/jIWSJEdR1tCBQnFclpijAi1+rxUfs39W01dJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T14:54:18Z"
    mac: ENC[AES256_GCM,data:qUIDjX4mNounAIUYdmCHyc8X8820WqDvt9gMFO+Xj+vXDg+2juxWpWXS7zFryW7gKiXTvwsbCpk3wKWVoh4edXJdKWRE1I5WqU0B5iCwm0KQlgeVs+rkJ7S3P+QhWBy4olkQgsC88lB5YRKkkJsfzpY1SoUP2AFU6olztMsgBGQ=,iv:ijHZ0RB8Y+Dv9WzIt67EepiVnGADmJ1YgsbXmacwLvo=,tag:ahzmq/EFSSJp4i0675/giA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3